server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CorsoDB
    username: postgres
    password: domelite
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

docenti:
  service:
    url: http://localhost:8080
discenti:
  service:
    url: http://localhost:8080
logging:
  level:
    root: INFO