server:
  port: 8081

corsiaparte:
  url: http://localhost:8081
docenti:
    url: http://localhost:8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CorsoDB
    username: postgres
    password: domelite
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect